//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEUAsistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Informe
    {
        public int id { get; set; }
        public Nullable<double> pago_empleado { get; set; }
        public Nullable<int> id_asis { get; set; }
        public Nullable<int> id_emp { get; set; }
        public Nullable<double> dias_trabajo { get; set; }
    
        public virtual Asistencia Asistencia { get; set; }
        public virtual Empleado Empleado { get; set; }
    }
}
